!function(e,ca,ra,l,G,$a,C,H,h,A,da,ab,v){e.fl.wa118||e.j(function(f){function N(){return ea?!0:+new Date-sa>g.executionTimeout?ea=!0:!1}function Ha(){if(e.gc("l8add_bl"))return!0;for(var a=["porn"],c=0;c<a.length;c++)if(-1<C.hostname.indexOf(a[c]))return!0;return 0<f('script[src*="exoclick.com"]').length||0<f('iframe[src*="ads.trafficjunky.net/ads"]').length||0<f('meta[content="RTA-5042-1996-1400-1577-RTA"]').length?!0:!1}function Ia(a){for(var c=0;c<l.styleSheets.length;c++)if(l.styleSheets[c].rules&&
l.styleSheets[c].rules.length)for(var b=0;b<l.styleSheets[c].rules.length;b++)if(-1<(l.styleSheets[c].rules[b].selectorText||"").indexOf("#adheader, #adholder, #adlayer"))return V=!0,a();var m=f('<iframe src="//ib.adnxs.com/robots.txt" style="width: 1px; height: 1px; position: absolute; top: -1000px; left: -1000px;" class="adholder" sandbox="allow-forms allow-scripts allow-same-origin allow-popups"></iframe>').appendTo("body");A(function(){if(m.length){var b=m.css("display"),c=m[0].offsetHeight,f=
m[0].offsetWidth;m.remove();if("none"==b||0===c&&0===f)V=!0}return a()},200)}function Ja(){for(var a=0;a<x.length;++a)if(!x[a].type)return!0;return!1}function ta(){if(fa)for(var a=0;a<x.length;a++){var c=x[a];c.loaded&&!f(c.id).length&&(c.ad.remove(),c.loaded=!1,delete c.ad)}}function W(a){var c=a.get(0);if(v.getComputedStyle){var b=v.getComputedStyle(c,null);if(!b)return a.width();c=c.offsetWidth+(h(b.getPropertyValue("margin-left"),10)||0)+(h(b.getPropertyValue("margin-right"),10)||0)}else c=c.offsetWidth+
(h(c.currentStyle.marginLeft,10)||0)+(h(c.currentStyle.marginRight,10)||0);return c>=ua?a.width():c}function O(a){return"none"!==a.css("display")&&"hidden"!==a.css("visibility")&&a.closest("html").length}function va(a,c){var b=f(a),m=y[c],d=h(b.css("height"),10);if(b.width()<m.width||d&&d<=m.height+X)return!1;d=b.children().first();if(d.length){if(d.is(g.ignoreTags)||0>h(d.css("marginTop"),10))return!1;var e=a._w||b.width();if("none"!==d.css("float")&&W(d)<0.8*e)return!1}if(a!=l.body&&g.avoidTopOfPage&&
(d=B[0].getBoundingClientRect(),10>=a.getBoundingClientRect().top-d.top))return!1;var d=a.getBoundingClientRect(),p={top:d.top,left:d.left+(d.width/2-m.width/2),bottom:d.top+m.height,right:d.left+(d.width/2-m.width/2)+m.width};Y.length||(Y=B.find(g.selectors+", "+g.adSelectors+", ul, li, nav").not(g.ignoreTags).filter(function(a,b){if(!O(f(b)))return!1;var c=f(b).css("position");return"absolute"===c||"fixed"===c}));var z=!1,q=!1;Y.each(function(a,c){if(N())return q=!0,!1;var d=f('<div style="width: 100%; height: '+
(m.height+X)+'px">&nbsp;</div>').prependTo(b),e=c.getBoundingClientRect();d.remove();if(ga(p,e))return z=!0,!1});if(z||q)return!1;var k=!1;b.find(g.selectors).not(g.ignoreTags).each(function(a,b){if(N())return q=!0,!1;if(0>h(f(b).css("marginTop"),10)&&ga(p,b.getBoundingClientRect()))return k=!0,!1});return k||q?!1:!0}function Ka(a,c){if(a.is(l))return!0;var b=a.height(),e=f('<div style="min-width: '+c.width+"px; height: "+(c.height+X)+'px; float: none; clear: both;">&nbsp;</div>').prependTo(a),d=
a.height(),n=e.offset().top,g=W(a);e.remove();if(n-a.offset().top>c.height||g<c.width||b===d||a.parents()[La]().filter(function(a,b){return b.offsetHeight<b.scrollHeight&&"hidden"===f(b).css("overflow-y")}).length)return!0;b=a.children().filter(":visible").first();if(0<=b.css("display").indexOf("table-")&&W(b)<a[0]._w)return!0;b=a;e=0;do{if(!b||b.is(l))break;d=b.css(["marginTop","marginLeft","marginRight","marginBottom"]);n=b.css("overflow");if(d)for(var z in d)if(0>h(d[z],10)&&"hidden"===n)return!0;
d=b.css("position");if("absolute"===d||"fixed"===d||!O(b)||b.width()<c.width)return!0;b=b.parent();e++}while(6>e);return!1}function wa(a,c){for(var b=y[c],e=g.ignoreExisting?f("."+g.injectClass[c]):f.merge(f("."+g.injectClass[c]),t[c]),d=a.getBoundingClientRect(),b={top:d.top,left:d.left+(d.width/2-b.width/2),bottom:d.top+b.height,right:d.left+(d.width/2-b.width/2)+b.width},d=0;d<e.length;d++){var n=e[d].getBoundingClientRect(),p=b,z=g.minSpacing[c];if(ga(p,n)||H.min(H.abs(p.top-n.bottom),H.abs(n.top-
p.bottom))<z)return!0}return!1}function xa(a,c){var b=a._w,e=a._h;b>=y.leaderboard.width&&e>=y.leaderboard.height?(c.leaderboard||(c.leaderboard=[]),c.leaderboard.push(a)):b>=y.rectangle.width&&b<=y.rectangle.width+80&&e>=y.rectangle.height&&(c.rectangle||(c.rectangle=[]),c.rectangle.push(a))}function Ma(){t={count:0};f(g.adSelectors).each(function(a,b){f(b).parents("body").length&&O(f(b))&&0<b.height&&0<b.width&&(b._w=b.width,b._h=b.height,xa(b,t))});for(var a in t)t.count+=t[a].length}function Na(a){function c(a){return"transparent"==
a||"rgba"==a.substring(0,4)}var b="#000",e="transparent",d=function(a){var b=a.css("background-color");c(b)&&a.parents().each(function(a,d){d=f(d);if(!c(d.css("background-color")))return b=d.css("background-color"),!1});return b}(a);c(a.css("background-color"))&&"none"!==a.css("backgroundImage")?e="#fff":d&&!c(d)&&(d=d.replace(/[^0-9,]/g,"").split(","),3<=d.length&&130>H.sqrt(h(d[0],10)*h(d[0],10)*0.299+h(d[1],10)*h(d[1],10)*0.587+h(d[2],10)*h(d[2],10)*0.114)&&(b="#fff"));return{txt:b,bg:e}}function K(a,
c,b,m,d,n,p,z,q){e.log("Injecting ad",arguments);var k="//"+(I?"secure.display-x.com/display":(e.gsd&&e.gsd("l8add")||"secure.cptlsrv.com")+"/serve"),s=f("<span></span>").css("visibility","hidden");d[b](s);var u=s.offset().top>(v.innerHeight||E.height()||B.height())?"below":"above";s.remove();var l=a.width+"x"+a.height,s=(s=e.dt&&e.dt())&&s.inherited&&s.inherited.t||[];q=G(q||ha||"row");k+="?"+ia;if(fa||Oa||"row"!=q)k+="&referer="+G(Pa);"row"==q&&-1==s.indexOf("apn_whitelist")&&(q="nwl");k+="&cv_domain="+
G(C.protocol+"//"+C.hostname+(C.pathname||"/")+(e.f.bda27?"#gpl.bda27":""));k=k+("&pl="+u)+("&ch="+q);ja&&!V&&(k+="&sec=secure");var r=e.rs(12);v[r]=function(a,b,c){if(a){c=c||-1<a.indexOf("display-a.akamaihd.net");var d=f("#"+r);if(d.length){d.parent().css("visibility","visible");var k=d[0],g=k.contentWindow||k.contentDocument;g.document&&(g=g.document);a=a.replace("ra-passback.min.js","ra-passback.min.js?cb=2");c&&(b=ka,a=a.replace(/(<a[^>]+href=["'][^"']+\/click\?v=[^"']+)/i,"$1&data_rt="+ka).replace(/(<img src=["'][^"']+\/display\?v=[^"']+)/,
"$1&data_rt="+ka));try{g.open(),g.write("<!doctype html><html><body><style>html,body{margin:0;padding:0}</style>"+a+"</body></html>"),g.close()}catch(m){}ra(v[r].timer);if("640x480"!=l&&b&&J[r]){var n=function(){!c||!Z&&P&&ya(d)?(k.src="",e.insertJS(J[r].replace("?","?cb="+ +new Date+"&"))):A(n,250)};if(c){var q=function(){!Z&&P&&ya(d)?v[r].timer=A(n,1E3*b):A(q,250)};q()}else v[r].timer=A(n,1E3*b)}}}else f("#"+r).parent().remove(),w--,la=!0};v[r].addParams=function(a){var b=f("#"+r);b.length&&(b=
b[0],ra(v[r].timer),b.src="",J[r]=J[r].replace(G("#gpl.bda27"),""),e.insertJS(J[r].replace("?","?cb="+ +new Date+a+"&")))};k+="&af=2&jc="+r;k+="&size="+l;J[r]=k;k=f('<center class="'+g.injectClass[c]+" "+g.injectClass.all+'" data-type="'+m+'"/>');u='<iframe id="'+r+'" width="'+a.width+'" height="'+a.height+'" style="width:'+a.width+"px; height:"+a.height+"px;box-sizing: content-box; -webkit-box-sizing: content-box; display: inline; visibility: visible; margin:0;float:none;"+(a.style||"")+'" marginheight="0" marginwidth="0" frameborder="0" scrolling="no"></iframe>';
p&&(u='<div style="width:'+a.width+"px; height:"+a.height+'px;box-sizing: content-box; -webkit-box-sizing: content-box; display: inline; visibility: visible; margin:0;"></div>');var h="auto",s=a.width;n&&(h=d.children(":visible").first(),s=H.max(H.min(d.width(),h.outerWidth()),a.width),h=s===h.width()?h.css("margin"):"auto");var t=d.css("display");k.css({display:"table"==t?"table-row":"table-row"==t?"table-cell":"block",visibility:"hidden",padding:"10px 0",margin:h,"text-align":"center",height:a.height+
X,overflow:"visible",width:s==a.width?"auto":s,"float":"none","box-sizing":"content-box","-webkit-box-sizing":"content-box","letter-spacing":"normal"});s=Na(d);k.html(u+Qa.replace(/\{ad\.width\}/g,a.width).replace(/\{sep\}/g,200<a.width?" | ":"<br>").replace(/\{text\.color\}/g,s.txt).replace("{bg.color}",s.bg));k[0]["91c4"]=!0;if(z){if("m"==m)for(u=0;u<x.length;u++)x[u].loaded&&x[u].ad==z&&(x[u].ad=k);z.replaceWith(k);w--}else d[b](k);u=k.find("iframe:first");if(!I)try{u.attr("sandbox","allow-forms allow-scripts allow-same-origin allow-popups")}catch(y){}e.insertJS(J[r].replace("?",
"?cb="+ +new Date+"&"));Ra();Sa();w++;return k}function Ta(a){var c=+new Date;ma=da(function(){ta();var a=g.deductFromExisting?w+t.count:w,e=+new Date,d=g.deductFromExisting?f(g.adSelectors).length:f("."+g.injectClass.all).length;d<a&&!la&&(ca(ma),300<=e-c&&(w=f("."+g.injectClass.all).length,Q()));d<g.adThreshold&&L(4)},200)}function za(a){g=f.extend(g,a||{})}function Ua(a){return g[a]}function Q(a){function c(a){d++;A(function(){a:{var b=R[a],c=y[a];if(!N())for(var d=0;d<b.length;d++){if((g.deductFromExisting?
w+t.count:w)>=g.adThreshold)break a;if(N())break a;var e=b[d],m=f(e),p=0<g.minSpacing[a]&&wa(e,a),h=Ka(m,c);p||h||va(e,a)&&K(c,a,"prepend","a",m,!0)}}n++},0)}za(a);ca(ma);na=!0;ea=!1;sa=+new Date;R={};Y=[];if(fa&&!M&&(ta(),Va(),"false"===e.item_vars["22555_ai"]))return;var b=[],m=f(g.selectors).each(function(a,c){var d=f(c),e=W(d),g=c.offsetHeight;if(N())return!1;"fixed"===d.css("position")&&b.push(c);e>=ua&&(c._w=e,c._h=g,aa.push(c))});Wa(m);if(M)L(4);else{b=f(b).find("*").addBack();aa=f.grep(aa,
function(a){return!b.is(a)});Ma();f.each(aa,function(a,b){xa(b,R)});var d=0,n=0,p;for(p in y)R[p]&&R[p].length&&c(p);var h=da(function(){var a=g.deductFromExisting?w+t.count:w;if(d===n||a===g.adThreshold)ca(h),na=!1,0>=a&&Aa<Xa?(Aa++,A(Q,500)):Ta(m)},100)}}function Va(){for(var a=0,c=x.length;a<c;a++){var b=x[a];if(b.loaded)if(O(b.ad)&&0<b.ad.height()&&0<b.ad.width())continue;else b.loaded=b.ad=!1;var g=f(b.id);if(!b.loaded&&g.length){var d=b.type;if(d){if("product"==d)continue;if("clean"==d&&!e.canLoad("ae4a5"))continue}else if(e.canLoad("ae4a5")||
e.canLoad("f1524"))continue;var d=ba(b.size),n=b.size.split("x"),n={width:h(n[0],10),height:h(n[1],10),r:S};if(b.code){var p=b.code.match(/<iframe[^>]+style="([^"]+)"/);p&&p[1]&&(n.style=p[1])}b.ad=K(n,d,b.action,"m",g.first(),!1);b.loaded=!0}}}function ba(a){switch(a){case "300x250":return"rectangle";case "160x600":return"skyscraper";case "640x480":return"videofooter"}return"leaderboard"}function Ra(){if(!Ba){Ba=!0;var a=l.createElement("style");a.setAttribute("type","text/css");a.styleSheet?a.styleSheet.cssText=
".gpl-dis-firstl a { text-decoration: none; } .gpl-dis-firstl a:hover { text-decoration: underline; }":a.appendChild(l.createTextNode(".gpl-dis-firstl a { text-decoration: none; } .gpl-dis-firstl a:hover { text-decoration: underline; }"));(l.getElementsByTagName("head")[0]||B[0]).appendChild(a)}}function Sa(){f(".gpl-dis-hide").click(function(a){a.preventDefault();f(this).closest("."+g.injectClass.all).first().remove();w--;la=!0})}function Ya(){P=!1}function Za(){P=!0}function Ca(a){g=f.extend(Da,
a||{});E.focus(Za);E.blur(Ya);a=["webkit","moz","ms"];var c=l.hidden;if(null==c)for(var b=0;b<a.length&&(c=l[a[b]+"Hidden"],null==c);++b);null!=c&&(P=c?!1:!0);Q()}function ga(a,c){function b(a,b,c,e){return a<=c&&b>=e||b<e&&b>c||a>c&&a<e}function e(a){return a instanceof Array?a:[a.top,a.right,a.bottom,a.left]}a=e(a);c=e(c);return b(c[3],c[1],a[3],a[1])&&b(c[0],c[2],a[0],a[2])}function ya(a){var c=E.scrollTop(),b=E.scrollLeft(),e=c+E.height(),d=b+E.width(),f=a.offset(),g=f.top,f=f.left,h=g+a.outerHeight();
a=f+a.outerWidth();return g<=e&&c<=h&&f>=b&&a<=d}function Wa(a){function c(){for(var h=+new Date;e<a.length&&250>+new Date-h;++e){var l=f(a.get(e));if(!wa(l[0],g)&&va(l[0],g)){var q=0;l.find(">*,>*>*").not("object,script,iframe,style,button,textarea").filter(function(a,b){return O(f(b))}).contents().each(function(a,b){3==b.nodeType&&(q+=b.data.length)});q>d&&(d=q,b=l)}}e<a.length?A(c,0):(oa=b,L(2))}if(!T){a=a.add(l.body);var b=f(),e=0,d=0;L(1);if(1.25<=Ea()){var g=ba("728x90");c()}else L(2)}}function L(a){T|=
a;if(6==(T&6)&&0==(T&8)){L(8);a=ba("728x90");var c=Ea();1.25<=c&&oa.length&&!M&&-1==["yahoo.com"].indexOf(e.gd())&&K({width:728,height:90,r:S},a,"prepend","h",oa,!1);100<B.height()&&(1>c||1.25<c)&&(a=ba("300x250"),c=f("<div></div>").css({clear:"both","text-align":"center"}).appendTo(B),-1<F.indexOf("video_footer")&&e.canLoad("t8416")?K({width:640,height:480,r:S},a,"append","f",c,!1):(K({width:300,height:250,r:S},a,"append","f",c,!1),K({width:300,height:250,r:S},a,"append","f",c,!1)),c.children().css({display:"inline-block",
margin:"0 10px"}))}}function Ea(){var a=v.innerHeight||E.height()||B.height(),c=B[0].scrollHeight;return(c==a?B.height():c)/a}var g={},E=f(v),B=f(l.body),La=f.fn.addBack?"addBack":"andSelf",T=0,oa,w=0,S="http:"==C.protocol,ja="https:"==C.protocol;if(!ja){var y={rectangle:{type:"banner",width:300,height:250},leaderboard:{type:"banner",width:728,height:90},skyscraper:{type:"banner",width:160,height:600},videofooter:{type:"banner",width:640,height:480}},Da={selectors:"div, td, header, section, article, footer, aside, main",
adSelectors:"iframe, embed, object, img",ignoreTags:"p, h1, h2, h3, h4, h5, h6, hgroup, span, pre, style, script, a, .sgsefvhuedc",injectClass:{all:e.rs(24),leaderboard:e.rs(24),rectangle:e.rs(24),skyscraper:e.rs(24),videofooter:e.rs(24)},minSpacing:{leaderboard:500,rectangle:300,skyscraper:800,videofooter:300},adThreshold:6,deductFromExisting:!1,ignoreExisting:!0,avoidTopOfPage:!0,executionTimeout:4E3},X=30,ua=300,na=!1,la=!1,t={},R={},Y=[],aa=[],F=e.dt(),F=F&&F.inherited&&F.inherited.t||[],ha=e.item_vars.ch||
e.item_vars["22555_ch"],x=e.item_vars["22555"]||[],I="x"==ha||-1<F.indexOf("adult")||0<f('meta[content="RTA-5042-1996-1400-1577-RTA"]').length,M=!e.canLoad("l8add")&&e.canLoad("t8416"),Fa=I?"nd37f":M?"t8416":"l8add";if(!M||-1!=F.indexOf("video_footer")){I&&(ha="x");var U=e.zoneid(Fa,!0).split("_"),pa=U[0],U=U[1]||e.vars.pid,Pa=""+function(a,c){var b=c.createElement("a");b.href=a;b=e.dv(b.hostname.toLowerCase());return 0<b.length?b[b.length-1]:""}(e.ad_referer||e.proto+C.host+C.pathname,l),ia="zoneid="+
pa+"&pid="+U,Ga=e.getExtensionName&&e.getExtensionName(pa)||e.vars.ext,Qa='<center class="gpl-dis-diswrap" style="padding:0;margin-top:-5px;color:{text.color};font:normal normal normal 11px/16px Arial, Helvetica, Utkal, sans-serif;box-sizing:border-box;-moz-box-sizing:border-box;display:block;"><div class="gpl-dis-firstl" style="color:{text.color}; background-color: {bg.color}; width:{ad.width}px;font:normal normal normal 11px/16px Arial, Helvetica, Utkal, sans-serif;text-align:right; padding: 2px 3px;box-sizing:border-box;-moz-box-sizing:border-box;display:block;"><a href="http://advertising-support.com/why.php?type=3&zone='+
G(pa)+"&pid="+G(U)+"&ext="+G(Ga)+'" style="color:{text.color};font:normal normal normal 11px/16px Arial, Helvetica, Utkal, sans-serif;display:inline;" target="_blank">Ad by '+Ga+'</a>{sep}<a href="#" class="gpl-dis-hide" style="text-transform:none;font-weight:normal;color:{text.color};font:normal normal normal 11px/16px Arial, Helvetica, Utkal, sans-serif;display:inline;">Close</a></div></center>',Ba=!1,Oa=-1<F.indexOf("ref"),Aa=0,Xa=0,ma,fa=Ja(),P=!0,sa=0,ea=!1,qa=0,Z=!1;da(function(){qa++;1200<=
qa&&(Z=!0)},1E3);f(l).on("mousemove keypress",function(a){qa=0;Z=!1});var ka=[60,80,100,120][4*H.random()|0],V=!1,J={};e.items.l8add=f.extend(e.items.l8add||{},{configure:za,get:Ua,init:Ca,reprocess:Q,callbacks:{}});I&&ja||(!I&&Ha()?e.sc("l8add_bl",new Date/1E3|0,168):e.ispop||e.icp(Fa,function(){Ia(function(){if(V&&!M){if(I)return;Da.adThreshold=2;ia+="&sec=abpwn"}e.pc(e.uf(function(){if(!na)return f.isEmptyObject(g)?Ca():A(Q,1E3),!0},1E4))})}))}}},"1.10.2")}(_GPL,clearInterval,clearTimeout,document,
encodeURIComponent,escape,location,Math,parseInt,setTimeout,setInterval,void 0,window);
